export const imagesMap = {
    hotel: [
      "/images/hotel_1.png",
      "/images/hotel_2.png",
      "/images/hotel_3.png",
      "/images/hotel_4.png",
      "/images/hotel_5.png",
      "/images/hotel_6.png",
      "/images/hotel_7.png",
      "/images/hotel_8.png",
      "/images/hotel_9.png",
    ],
    teoola: [
      "/images/teoola_1.png",
      "/images/teoola_2.png",
      "/images/teoola_3.png",
      "/images/teoola_4.png",
      "/images/teoola_5.png",
      "/images/teoola_6.png",
      "/images/teoola_7.png",
      "/images/teoola_8.png",
      "/images/teoola_9.png",
      "/images/teoola_10.png",
    ],
  };